/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentSection: typeof import('./src/components/welink/settings/AgentSection.vue')['default']
    CodehubSettingsCard: typeof import('./src/components/codehub/CodehubSettingsCard.vue')['default']
    ConfigTab: typeof import('./src/components/welink/ConfigTab.vue')['default']
    ControlBar: typeof import('./src/components/welink/ControlBar.vue')['default']
    ConversationListPanel: typeof import('./src/components/welink/messages/ConversationListPanel.vue')['default']
    CreateTab: typeof import('./src/components/group/CreateTab.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GroupHistoryTab: typeof import('./src/components/group/GroupHistoryTab.vue')['default']
    HistoryTab: typeof import('./src/components/welink/HistoryTab.vue')['default']
    InboxTab: typeof import('./src/components/welink/InboxTab.vue')['default']
    KnowledgeCard: typeof import('./src/components/welink/KnowledgeCard.vue')['default']
    LlmSettingsCard: typeof import('./src/components/welink/LlmSettingsCard.vue')['default']
    MessagesTab: typeof import('./src/components/welink/MessagesTab.vue')['default']
    MrDetailPanel: typeof import('./src/components/codehub/MrDetailPanel.vue')['default']
    MrStateBadge: typeof import('./src/components/codehub/MrStateBadge.vue')['default']
    PendingJobsPanel: typeof import('./src/components/welink/messages/PendingJobsPanel.vue')['default']
    RagSettingsCard: typeof import('./src/components/welink/RagSettingsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafetySection: typeof import('./src/components/welink/settings/SafetySection.vue')['default']
    SedimentCard: typeof import('./src/components/welink/SedimentCard.vue')['default']
    SettingsCard: typeof import('./src/components/welink/SettingsCard.vue')['default']
    SkillsSection: typeof import('./src/components/welink/settings/SkillsSection.vue')['default']
    TemplateTab: typeof import('./src/components/group/TemplateTab.vue')['default']
    TimelinePanel: typeof import('./src/components/welink/messages/TimelinePanel.vue')['default']
    TraceTab: typeof import('./src/components/welink/TraceTab.vue')['default']
    UpdateSettingsCard: typeof import('./src/components/update/UpdateSettingsCard.vue')['default']
    WizardPanel: typeof import('./src/components/welink/WizardPanel.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
